site_name: beep beep technology

theme:
  name: material
  logo: assets/images/beepbeep_logo_white.png
  #icon:
  #  logo: material/elephant
  favicon: assets/images/beepbeep_logo_white.png

nav:
  - Overview: 'index.md'
  - What We Build: 'what_we_build.md'
  - 'How We Build It':
    - Inbound Automation: 'inbound.md'
    - Transformation: 'transformation.md'
#    - Augmentation: 'augmentation.md'
    - Outbound Automation: 'outbound.md'
  - How We Work: 'how_we_work.md'

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

#repo_url: https://github.com/datafunctions/datafunctions.github.io

google_analytics:
  - UA-119865580-5
  - auto

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@beepbeep.technology