site_name: beep beep technology

theme:
  name: material

nav:
  - Overview: 'index.md'
  - What We Build: 'what_we_build.md'
  - 'How We Build It':
    - Inbound Automation: 'inbound.md'
    - Transformation: 'transformation.md'
    - Augmentation: 'augmentation.md'
    - Outbound Automation: 'outbound.md'
  - How We Work: 'how_we_work.md'

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences

#repo_url: https://github.com/datafunctions/datafunctions.github.io

google_analytics:
  - UA-119865580-5
  - auto

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@beepbeep.technology